### ISSUE TITLE
problem with example usage for pulling data

### ISSUE THREAD

**Issue by ben-domingue** [redivis/redivis-r#12]
Hi, 
I am unable to pull data from Redivis using the syntax in the 'Getting started' page. The error is shown below. 

```
> Sys.getenv('REDIVIS_API_TOKEN')
[omitted, just want to emphasize that i've set token]
> 
> data <- (
    redivis::organization("Demo")
    $dataset("CMS 2014 Medicare Data")
    $table("Hospice providers")
    $to_tibble(max_results=100) 
)

Error in make_request(method = "GET", path = path, parse_response = TRUE,  : 
  Invalid scope on credentials. This method requires scope: data.metadata
```
I'm able to generate this error on both my machines; obviously that might mean I'm just making the same mistake in both places. 

Thanks in advance for any assistance!

**Comment by imathews** [comment]
This has been resolved - thanks for the report Ben!
